import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SimpleHeader from '@/components/SimpleHeader'
import ReadingProgress from '@/components/ReadingProgress'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  modal,
  rules
}: {
  children: React.ReactNode
  modal: React.ReactNode // @ ---- Параллельный роут
  rules: React.ReactNode // @ ---- Параллельный роут
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <header>главный Layout</header> */}
        {/* {map} */}
        {/* {rules} */}
        <SimpleHeader />
        {children}
        <footer className=" flex justify-center">
          <h1 className=" text-2xl text-red-600">Footer</h1>
        </footer>
        {modal}
      </body>
    </html>
  )
}
